# Generated by Django 5.2.1 on 2025-05-10 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam quyidagicha bo'lishi kerak:+998xxxxxxxxx", regex='^\\+998\\d{9}')]),
        ),
    ]
