# Generated by Django 5.2.1 on 2025-05-10 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_teacher_subject_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam quyidagicha bo'lishi kerak:+998xxxxxxxxx", regex='^\\+998\\d{9}')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam quyidagicha bo'lishi kerak:+998xxxxxxxxx", regex='^\\+998\\d{9}')]),
        ),
    ]
